### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by stesie**
This is a major code cleanup I'd like to propose before tackling issue #72 which is going to introduce new classes and a trait.

Currently the v8js.cc file is rather messy IMHO as it not only holds everything related to our V8Js main class, but also V8Object & V8Function classes as well as all exception classes + v8 initialization.
I've now split all that stuff into seperate files (v8js_class.cc, v8js_v8object_class.cc, v8js_exceptions.cc + non class stuff in v8js_timer.cc & v8js_v8.cc)

Besides I found the similarly named handler functions relating to v8js (php_v8js_XXX) and v8object (php_v8js_v8_XXX) classes rather confusing and hence renamed the latter to v8js_v8object_XXX (i.e. with "object" term in it)

Also we had a huge mess with symbols beginning with "php_v8js_" and just  "v8js_"; e.g. `php_v8js_ctx`, `php_v8js_execute_string` as opposed to `v8js_to_zval`, `v8js_persistent_obj_t` et al.
So I removed all the leading php_ prefixes.

@preillyme @cscott please let me know what you think about that change; if you agree or if I go too far (especially with the renaming of existing symbols, not just moving them around)

cheers
  ~stesie

### CODE REVIEW

**Comment by preillyme** [comment]
:+1: have you reviewed this at all @cscott ?

**Comment by preillyme** [comment]
@stesie do you still want this merged? It looks good to me.

**Comment by stesie** [comment]
I'd still like to merge this, but haven't felt the urgent need to do so without feedback.  I'm currently spending some time off V8Js and besides a bit stuck on the other cleanup ticket (#72); hence I probably would have followed up here if the other patches are ready.

**Comment by preillyme** [comment]
@stesie okay I've merged it. Hopefully we can figure out the other cleanup ticket (#72).

**Pull request merged**
